name: HuaweiCloud AKSK Check + List VPC
on:
  workflow_dispatch:

jobs:
  signed-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Huawei Cloud credentials
        run: |
          echo "HW_AK=${{ secrets.HW_AK }}" >> $GITHUB_ENV
          echo "HW_SK=${{ secrets.HW_SK }}" >> $GITHUB_ENV
          echo "HW_REGION=${{ secrets.HW_REGION }}" >> $GITHUB_ENV
          echo "HW_PROJECT_ID=${{ secrets.HW_PROJECT_ID }}" >> $GITHUB_ENV

      # Step 1: Verify AK/SK by calling IAM list projects
      - name: Verify AK/SK by signed SDK call (IAM list projects)
        run: |
          pip install --upgrade pip
          pip install "huaweicloudsdkcore>=3.1.99" "huaweicloudsdkiam>=3.1.99"
          python - <<'PY'
          import os
          from huaweicloudsdkcore.auth.credentials import BasicCredentials
          from huaweicloudsdkcore.exceptions import exceptions
          from huaweicloudsdkcore.http.http_config import HttpConfig
          from huaweicloudsdkiam.v3 import IamClient, KeystoneListProjectsRequest

          ak = os.getenv("HW_AK")
          sk = os.getenv("HW_SK")
          region = os.getenv("HW_REGION")
          project_id = os.getenv("HW_PROJECT_ID")

          endpoint = f"https://iam.{region}.myhuaweicloud.com"
          http_config = HttpConfig.get_default_config()
          cred = BasicCredentials(ak, sk, project_id)
          client = (
              IamClient.new_builder()
              .with_http_config(http_config)
              .with_credentials(cred)
              .with_endpoint(endpoint)
              .build()
          )

          resp = client.keystone_list_projects(KeystoneListProjectsRequest())
          projects = resp.projects or []
          print(f"✅ Signed request succeeded. Number of projects: {len(projects)}")
          for p in projects:
              print(f"- {p.name:20s} | ID: {p.id}")
          PY

      # Step 2: List VPC names (read-only)
      - name: List VPC names
        run: |
          pip install "huaweicloudsdkvpc>=3.1.99"
          python - <<'PY'
          import os
          from huaweicloudsdkcore.auth.credentials import BasicCredentials
          from huaweicloudsdkcore.http.http_config import HttpConfig
          from huaweicloudsdkvpc.v3 import VpcClient, ListVpcsRequest

          ak = os.getenv("HW_AK")
          sk = os.getenv("HW_SK")
          region = os.getenv("HW_REGION")
          project_id = os.getenv("HW_PROJECT_ID")

          endpoint = f"https://vpc.{region}.myhuaweicloud.com"
          http_config = HttpConfig.get_default_config()
          cred = BasicCredentials(ak, sk, project_id)
          client = (
              VpcClient.new_builder()
              .with_http_config(http_config)
              .with_credentials(cred)
              .with_endpoint(endpoint)
              .build()
          )

          resp = client.list_vpcs(ListVpcsRequest(limit=100))
          vpcs = resp.vpcs or []
          if not vpcs:
              print("No VPCs found in this region/project.")
          else:
              print(f"✅ Found {len(vpcs)} VPC(s):")
              for v in vpcs:
                  print(f"- {v.name:20s} | ID: {v.id} | CIDR: {v.cidr}")
          PY
